name: peton
description: Moaon - peton

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ################
  # 공식 플러그인 #
  ###############
  # IOS icons
  cupertino_icons: ^1.0.0
  # 네트워크 연결 확인
  connectivity: ^2.0.2
  # json 직렬화, 역직렬화 코드 관련
  # + json_serializable, build_runner
  json_annotation: ^3.1.1
  # 안드로이드 인텐트 플러그인
  android_intent: ^0.3.7+7
  # SQLite 데이터베이스
  sqflite: ^1.3.2+1
  # 경로 설정 플러그인
  path_provider: ^1.6.24
  path: ^1.7.0
  # 설정 변수
  shared_preferences: ^0.5.12+4
  # firebase
  # dynamic link, messaging
  firebase_dynamic_links: ^0.6.3
  share: ^0.6.5+4
  firebase_core: ^0.5.3
  firebase_messaging: ^7.0.3
  meta: ^1.2.4
  # admob
  firebase_admob: ^0.10.3
  admob_flutter: ^1.0.1
  # 알림창
  flutter_local_notifications: ^3.0.2
  flutter_local_notifications_platform_interface: ^2.0.0+1
  platform: ^2.2.1
  # Carousel Slider
  carousel_slider: ^3.0.0
  # listview, gridview 애니매이션
  auto_animated: ^2.1.0
  # 검색 바 (dialog 형식)
  search_choices: ^1.0.17
  # url 링크
  url_launcher: ^5.7.10
  # font_awesome_flutter 아이콘
  font_awesome_flutter: ^8.11.0
  # 확장 가능한 appbar
  customizable_space_bar: ^0.1.0
  # 앱 패키지 정보 가져오기
  package_info: ^0.4.3+4
  # http
  http: ^0.12.2
  # slidable using for Dismissible
  flutter_slidable: ^0.5.7

  #################
  # 비공식 플러그인 #
  #################
  # http 클라이언트
  dio: ^3.0.9
  # 유튜브 영상 플레이어 (use iframe)
  # youtube_player_flutter: ^7.0.0+6
  youtube_player_iframe: ^1.1.0
  # 스크롤 시 새로고침
  pull_to_refresh: ^1.6.3
  # 이미지 플러그인(로딩, 성공, 실패)
  extended_image: ^1.5.0
  # 테마 설정
  adaptive_theme: ^1.1.0
  # text size 자동 조절
  auto_size_text: ^2.1.0
  # 버전 정보 크롤링용
  web_scraper: ^0.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.0
  build_runner: ^1.10.6
  flutter_launcher_icons: ^0.8.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/mainTitleBlack.png
    - assets/mainTitleWhite.png

#  assets:
#    - lib/assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Noto Serif KR
      fonts:
        - asset: fonts/NotoSerifKR-Black.otf
        - asset: fonts/NotoSerifKR-Bold.otf
        - asset: fonts/NotoSerifKR-ExtraLight.otf
        - asset: fonts/NotoSerifKR-Light.otf
        - asset: fonts/NotoSerifKR-Medium.otf
        - asset: fonts/NotoSerifKR-Regular.otf
        - asset: fonts/NotoSerifKR-SemiBold.otf
          weight: 700